In [3]:
import pandas as pd 
import nfl_data_py as nfl
import os

In [4]:
years = list(range(2005,2026))
schedules = nfl.import_schedules(years)
print(f"Partidos cargados: {len(schedules)}")

display(schedules.head())

Partidos cargados: 5698

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,...,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
1578,2005_01_OAK_NE,2005,REG,1,2005-09-08,Thursday,09:00,OAK,20.0,NE,...,0.0,00-0003292,00-0019596,Kerry Collins,Tom Brady,Norv Turner,Bill Belichick,Tony Corrente,BOS00,Gillette Stadium
1579,2005_01_HOU_BUF,2005,REG,1,2005-09-11,Sunday,13:00,HOU,7.0,BUF,...,0.0,00-0020608,00-0022912,David Carr,J.P. Losman,Dom Capers,Mike Mularkey,Ron Winter,BUF00,Ralph Wilson Stadium
1580,2005_01_NO_CAR,2005,REG,1,2005-09-11,Sunday,13:00,NO,23.0,CAR,...,15.0,00-0001823,00-0004161,Aaron Brooks,Jake Delhomme,Jim Haslett,John Fox,Tom White,CAR00,Bank of America Stadium
1581,2005_01_CIN_CLE,2005,REG,1,2005-09-11,Sunday,13:00,CIN,27.0,CLE,...,5.0,00-0021429,00-0004293,Carson Palmer,Trent Dilfer,Marvin Lewis,Romeo Crennel,Scott Green,CLE00,Cleveland Browns Stadium
1582,2005_01_SEA_JAX,2005,REG,1,2005-09-11,Sunday,13:00,SEA,14.0,JAX,...,7.0,00-0007091,00-0022177,Matt Hasselbeck,Byron Leftwich,Mike Holmgren,Jack Del Rio,Ed Hochuli,JAX00,Alltel Stadium

In [5]:
features = ["game_id", "season", "game_type", "week", "away_team", "away_score", "home_team", "home_score", "result"]
schedules[features].head()
schedules[features].describe()

            season         week  away_score   home_score       result
count  5698.000000  5698.000000  5698.00000  5698.000000  5698.000000
mean   2015.126887     9.617410    21.34205    23.538786     2.196736
std       6.092138     5.370721     9.98458    10.242281    14.633360
min    2005.000000     1.000000     0.00000     0.000000   -49.000000
25%    2010.000000     5.000000    14.00000    17.000000    -7.000000
50%    2015.000000    10.000000    21.00000    23.000000     3.000000
75%    2020.000000    14.000000    28.00000    30.000000    11.000000
max    2025.000000    22.000000    59.00000    70.000000    59.000000

In [6]:
schedules[features].head()

,game_id,season,game_type,week,away_team,away_score,home_team,home_score,result
1578,2005_01_OAK_NE,2005,REG,1,OAK,20.0,NE,30.0,10.0
1579,2005_01_HOU_BUF,2005,REG,1,HOU,7.0,BUF,22.0,15.0
1580,2005_01_NO_CAR,2005,REG,1,NO,23.0,CAR,20.0,-3.0
1581,2005_01_CIN_CLE,2005,REG,1,CIN,27.0,CLE,13.0,-14.0
1582,2005_01_SEA_JAX,2005,REG,1,SEA,14.0,JAX,26.0,12.0

In [7]:
ruta_salida = "../data/nfl_partidos_historico.csv"
schedules[features].to_csv(ruta_salida, index=False)

In [8]:
schedules.head(10)

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,...,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
1578,2005_01_OAK_NE,2005,REG,1,2005-09-08,Thursday,09:00,OAK,20.0,NE,...,0.0,00-0003292,00-0019596,Kerry Collins,Tom Brady,Norv Turner,Bill Belichick,Tony Corrente,BOS00,Gillette Stadium
1579,2005_01_HOU_BUF,2005,REG,1,2005-09-11,Sunday,13:00,HOU,7.0,BUF,...,0.0,00-0020608,00-0022912,David Carr,J.P. Losman,Dom Capers,Mike Mularkey,Ron Winter,BUF00,Ralph Wilson Stadium
1580,2005_01_NO_CAR,2005,REG,1,2005-09-11,Sunday,13:00,NO,23.0,CAR,...,15.0,00-0001823,00-0004161,Aaron Brooks,Jake Delhomme,Jim Haslett,John Fox,Tom White,CAR00,Bank of America Stadium
1581,2005_01_CIN_CLE,2005,REG,1,2005-09-11,Sunday,13:00,CIN,27.0,CLE,...,5.0,00-0021429,00-0004293,Carson Palmer,Trent Dilfer,Marvin Lewis,Romeo Crennel,Scott Green,CLE00,Cleveland Browns Stadium
1582,2005_01_SEA_JAX,2005,REG,1,2005-09-11,Sunday,13:00,SEA,14.0,JAX,...,7.0,00-0007091,00-0022177,Matt Hasselbeck,Byron Leftwich,Mike Holmgren,Jack Del Rio,Ed Hochuli,JAX00,Alltel Stadium
1583,2005_01_NYJ_KC,2005,REG,1,2005-09-11,Sunday,13:00,NYJ,7.0,KC,...,12.0,00-0019559,00-0006355,Chad Pennington,Trent Green,Herm Edwards,Dick Vermeil,Larry Nemmers,KAN00,Arrowhead Stadium
1584,2005_01_DEN_MIA,2005,REG,1,2005-09-11,Sunday,13:00,DEN,10.0,MIA,...,0.0,00-0013042,00-0005589,Jake Plummer,Gus Frerotte,Mike Shanahan,Nick Saban,Bill Leavy,MIA00,Dolphin Stadium
1585,2005_01_TB_MIN,2005,REG,1,2005-09-11,Sunday,13:00,TB,24.0,MIN,...,NaN,00-0006423,00-0003739,Brian Griese,Daunte Culpepper,Jon Gruden,Mike Tice,Mike Carey,MIN00,Hubert H. Humphrey Metrodome
1586,2005_01_TEN_PIT,2005,REG,1,2005-09-11,Sunday,13:00,TEN,7.0,PIT,...,5.0,00-0011024,00-0022924,Steve McNair,Ben Roethlisberger,Jeff Fisher,Bill Cowher,Gerry Austin,PIT00,Heinz Field
1587,2005_01_CHI_WAS,2005,REG,1,2005-09-11,Sunday,13:00,CHI,7.0,WAS,...,0.0,00-0023541,00-0021379,Kyle Orton,Patrick Ramsey,Lovie Smith,Joe Gibbs,Terry McAulay,WAS00,FedExField

In [9]:
schedule_2026 = nfl.import_schedules([2026])
sch_reg_2026 = schedule_2026[schedule_2026["game_type"] == "REG"].copy()

total_partidos_2026 = len(sch_reg_2026)
partidos_pendientes = sch_reg_2026['home_score'].isna().sum()

print(f"🏈 Partidos de temporada regular 2026 encontrados: {total_partidos_2026} (Esperados: 272)")
print(f"⏳ Partidos pendientes por jugar (sin marcador): {partidos_pendientes}")

🏈 Partidos de temporada regular 2026 encontrados: 272 (Esperados: 272)
⏳ Partidos pendientes por jugar (sin marcador): 272

In [10]:
ruta_2026 = "../data/nfl_calendario_2026.csv"
sch_reg_2026.to_csv(ruta_2026, index=False)